In [14]:
import numpy as np
import gym
import random, time
from IPython.display import clear_output

In [15]:
env = gym.make("FrozenLake-v1")

In [16]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n
q_table = np.zeros((state_space_size, action_space_size))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [17]:
# parameters
num_episodes = 10000
max_steps_per_episode = 100
learning_rate = 0.1
discount_rate = 0.99
exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001

In [18]:
rewards_all_episodes = []

#Implementing the Qlearning algorithm

for episode in range(num_episodes):
    state = env.reset()
    done = False
    rewards_current_episode = 0

    for step in range(max_steps_per_episode):

        #Exploration-Exploitation tradeoff
        exploration_rate_threshold = random.uniform(0,1)
        if exploration_rate_threshold > exploration_rate:
            #the agent will exploit the environment and choose the best
            #possible action that maximises the Q value
            action = np.argmax(q_table[state, :])
        else:
            # the agent will explore the environment and sample action from the
            # environment
            action = env.action_space.sample()
        
        new_state, reward, done, truncated,  info = env.step(action)

        # updation of the Q table 
        q_table[state, action] = q_table[state,action]*(1-learning_rate) + learning_rate*(reward + discount_rate*np.max(q_table[new_state, :]))
        state = new_state
        rewards_current_episode += reward

        if done==True:
            break
    
    exploration_rate = min_exploration_rate + \
        (max_exploration_rate - min_exploration_rate)*np.exp(-exploration_decay_rate*episode)

    rewards_all_episodes.append(rewards_current_episode) 

    #Calculate and print the average reward per thousand episodes 
    rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes), num_episodes/1000)
    count = 1000
    print("**********Average reward per thousand episode*********\n")
    for r in rewards_per_thousand_episodes:
        print(count, ": ", str(sum(r/1000)))
        count+=1000

    #Print updated Q table 
    print("\n\n******Q-TABLE*******\n")
    print(q_table)

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices